pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build') {
            steps {
                bat 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                bat 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                bat 'echo Delivering application...'
                bat 'copy target\\my-app-1.0-SNAPSHOT.jar target\\my-app-delivered.jar'
                bat 'echo Delivery complete: target\\my-app-delivered.jar'
            }
        }
    }
}
